# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from schemas._gen import live_store_pb2 as live__store__pb2


class LiveStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushGroup = channel.unary_unary(
                '/rollout_fabric.live_store.LiveStore/PushGroup',
                request_serializer=live__store__pb2.PushGroupRequest.SerializeToString,
                response_deserializer=live__store__pb2.PushGroupResponse.FromString,
                )
        self.GetBatch = channel.unary_unary(
                '/rollout_fabric.live_store.LiveStore/GetBatch',
                request_serializer=live__store__pb2.GetBatchRequest.SerializeToString,
                response_deserializer=live__store__pb2.GetBatchResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/rollout_fabric.live_store.LiveStore/GetMetrics',
                request_serializer=live__store__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=live__store__pb2.GetMetricsResponse.FromString,
                )
        self.NotifyPolicyVersion = channel.unary_unary(
                '/rollout_fabric.live_store.LiveStore/NotifyPolicyVersion',
                request_serializer=live__store__pb2.NotifyPolicyVersionRequest.SerializeToString,
                response_deserializer=live__store__pb2.Ack.FromString,
                )


class LiveStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyPolicyVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiveStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.PushGroup,
                    request_deserializer=live__store__pb2.PushGroupRequest.FromString,
                    response_serializer=live__store__pb2.PushGroupResponse.SerializeToString,
            ),
            'GetBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatch,
                    request_deserializer=live__store__pb2.GetBatchRequest.FromString,
                    response_serializer=live__store__pb2.GetBatchResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=live__store__pb2.GetMetricsRequest.FromString,
                    response_serializer=live__store__pb2.GetMetricsResponse.SerializeToString,
            ),
            'NotifyPolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyPolicyVersion,
                    request_deserializer=live__store__pb2.NotifyPolicyVersionRequest.FromString,
                    response_serializer=live__store__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rollout_fabric.live_store.LiveStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LiveStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.live_store.LiveStore/PushGroup',
            live__store__pb2.PushGroupRequest.SerializeToString,
            live__store__pb2.PushGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.live_store.LiveStore/GetBatch',
            live__store__pb2.GetBatchRequest.SerializeToString,
            live__store__pb2.GetBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.live_store.LiveStore/GetMetrics',
            live__store__pb2.GetMetricsRequest.SerializeToString,
            live__store__pb2.GetMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyPolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.live_store.LiveStore/NotifyPolicyVersion',
            live__store__pb2.NotifyPolicyVersionRequest.SerializeToString,
            live__store__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
