# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rollout_fabric.schemas._gen import policy_registry_pb2 as policy__registry__pb2


class PolicyRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishPolicyVersion = channel.unary_unary(
                '/rollout_fabric.policy_registry.PolicyRegistry/PublishPolicyVersion',
                request_serializer=policy__registry__pb2.PublishPolicyVersionRequest.SerializeToString,
                response_deserializer=policy__registry__pb2.PublishPolicyVersionResponse.FromString,
                )
        self.GetLatestVersion = channel.unary_unary(
                '/rollout_fabric.policy_registry.PolicyRegistry/GetLatestVersion',
                request_serializer=policy__registry__pb2.GetLatestVersionRequest.SerializeToString,
                response_deserializer=policy__registry__pb2.VersionInfo.FromString,
                )
        self.SubscribeVersionUpdates = channel.unary_stream(
                '/rollout_fabric.policy_registry.PolicyRegistry/SubscribeVersionUpdates',
                request_serializer=policy__registry__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=policy__registry__pb2.PolicyVersionSnapshot.FromString,
                )
        self.RegisterPolicyNamespace = channel.unary_unary(
                '/rollout_fabric.policy_registry.PolicyRegistry/RegisterPolicyNamespace',
                request_serializer=policy__registry__pb2.RegisterPolicyNamespaceRequest.SerializeToString,
                response_deserializer=policy__registry__pb2.Ack.FromString,
                )


class PolicyRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishPolicyVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeVersionUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPolicyNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishPolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishPolicyVersion,
                    request_deserializer=policy__registry__pb2.PublishPolicyVersionRequest.FromString,
                    response_serializer=policy__registry__pb2.PublishPolicyVersionResponse.SerializeToString,
            ),
            'GetLatestVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestVersion,
                    request_deserializer=policy__registry__pb2.GetLatestVersionRequest.FromString,
                    response_serializer=policy__registry__pb2.VersionInfo.SerializeToString,
            ),
            'SubscribeVersionUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeVersionUpdates,
                    request_deserializer=policy__registry__pb2.SubscribeRequest.FromString,
                    response_serializer=policy__registry__pb2.PolicyVersionSnapshot.SerializeToString,
            ),
            'RegisterPolicyNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPolicyNamespace,
                    request_deserializer=policy__registry__pb2.RegisterPolicyNamespaceRequest.FromString,
                    response_serializer=policy__registry__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rollout_fabric.policy_registry.PolicyRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PolicyRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishPolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.policy_registry.PolicyRegistry/PublishPolicyVersion',
            policy__registry__pb2.PublishPolicyVersionRequest.SerializeToString,
            policy__registry__pb2.PublishPolicyVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.policy_registry.PolicyRegistry/GetLatestVersion',
            policy__registry__pb2.GetLatestVersionRequest.SerializeToString,
            policy__registry__pb2.VersionInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeVersionUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rollout_fabric.policy_registry.PolicyRegistry/SubscribeVersionUpdates',
            policy__registry__pb2.SubscribeRequest.SerializeToString,
            policy__registry__pb2.PolicyVersionSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterPolicyNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rollout_fabric.policy_registry.PolicyRegistry/RegisterPolicyNamespace',
            policy__registry__pb2.RegisterPolicyNamespaceRequest.SerializeToString,
            policy__registry__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
